camera/horizontal_fov: 56.0
camera/vertical_fov: 42.0

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.50
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 4
aep/gain/zero: 16
aep/gain/lambda: 1
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-10.0, -10.0,  0.0]
boundary/max: [ 10.0,  10.0,  2.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"

