camera/horizontal_fov: 56.0
camera/vertical_fov: 42.0

raycast/dr:     0.2
raycast/dphi:   20
raycast/dtheta: 20

system/bbx/r: 0.50
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 7
aep/gain/zero: 0.1
aep/gain/lambda: 0.5
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 3
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 50
aep/tree/cutoff_iterations: 50

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-20.0, -20.0,  0.0]
boundary/max: [ 20.0, 20.0,  2.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"

