camera/horizontal_fov: 115.0
camera/vertical_fov: 60.0

raycast/dr:     0.2
raycast/dphi:   45
raycast/dtheta: 45

system/bbx/r: 0.7
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 7
aep/gain/zero: 0.50
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 3
aep/tree/max_sampling_radius: 7.5
aep/tree/initial_iterations: 50
aep/tree/cutoff_iterations: 200

rrt/min_nodes: 1000

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-1.0, -24.0, -4.0]
boundary/max: [ 30.0,  7.0,  2.8]
# boundary/min: [-30.0, -30.0,  0.0]
# boundary/max: [ 30.0,  30.0,  30.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "fcu"
world_frame: "map"

